#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# Information about the commits which are being pushed is supplied as arguments
# but Gnitpick does not need them, so they are just ignored.
#
# Install this script with:
#   cd .git/hooks
#   ln -s ../../git-hooks/pre-push

# Abort on all errors
set -e

if [ -f ./gnitpick.py ]
then
  # This hook always runs out of the repository root, no need to check $PWD
  # or adjust path to Gnitpick.
  ./gnitpick.py
else
  # If Gnitpick is installed system wide:
  gnitpick
fi

exit 0
