name: "Nitpick git commits"

on: [push]

jobs:
  nitpick:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Run gnitpick
        uses: Seravo/gnitpick@feature/container
