name: "Nitpick git commits"

on: [push]

env:
  PYTHON_VERSION: 3.9

jobs:
  nitpick:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run gnitpick
        run: python3 gnitpick.py --verbose
