name: "Lint python code"

on: [push]

env:
  PYTHON_VERSION: 3.9

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip3 install flake8

      - name: Lint code
        run: flake8
